swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: "localhost:3001"
basePath: "/api/v1"
schemes:
  - http
paths:
  /transactions:
    get:
      tags:
        - transactions
      summary: Transactions of the month
      description: Get transactions of the month for the connected user
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: object
          description: Transactions attributes
          schema:
            $ref: '#/definitions/Transactions'
      produces:
      - "application/json"
      
      responses:
        '200':
          description: Transactions information retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - transactions
      summary: Detailed transaction information
      description: Get more information about a transaction
      parameters:
        - in: header
          name: TransactionId
          description: Transaction Id 
          type: string
          required: true
        - in: body
          name: object
          description: Transaction attributes
          schema:
                $ref: '#/definitions/Transaction'
      produces:
      - "application/json"
      
      responses:
        '200':
          description: Transaction information retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error
    put:
      tags:
        - transactions
      summary: Update transaction 
      description: Update information about a transaction
      parameters:
        - in: body
          name: TransactionId
          description: Transaction Id 
          type: string
          required: true
          schema:
                $ref: '#/definitions/Transaction'
      produces:
      - "application/json"
      
      responses:
        '200':
          description: Transaction information retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error

    delete:
      tags:
        - transactions
      summary: Delete transaction 
      description: Delete a transaction
      parameters:
        - in: body
          name: TransactionId
          description: Transaction Id 
          type: string
          required: true
          schema:
                $ref: '#/definitions/Transaction'
      produces:
      - "application/json"
      
      responses:
        '200':
          description: Transaction information retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error

definitions:
  Transactions:
    properties:
  TransactionsResponse:
    properties:
  Transaction:
    properties:
  TransactionResponse:
    properties: 
    


