swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: "localhost:3001"
basePath: "/api/v1"
schemes:
  - http
paths:
  /user/transactions:
    get:
      tags:
        - transactions
      summary: Transactions of the month
      description: Get transactions of the month for the connected user
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
      - "application/json"
      responses:
        '200':
          description: Transactions information retrieved successfully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error
  /user/transactions/{transactionId}:
    get:
      tags:
        - transactions
      summary: Detailed transaction information
      description: Get more information about a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
      - "application/json"
      responses:
        '200':
          description: Transaction information retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error
    put:
      tags:
        - transactions
      summary: Update transaction 
      description: Update category and/or notes of a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
        - in: body
          name: body
          description: send transaction information
          required: true
          schema:
            $ref: '#/definitions/UpdateTransaction'
      produces:
      - "application/json"
      responses:
        '200':
          description: Transaction successfully updated
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error
    delete:
      tags:
        - transactions
      summary: Delete transaction 
      description: Delete a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: integer
      produces:
      - "application/json"
      responses:
        '200':
          description: Transaction successfully deleted
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error
definitions:
  TransactionsResponse:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email: 
        type: string
      transactions:
        type: object
  TransactionResponse:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
      description: 
        type: string
      amount:
        type: integer
      type:
        type: string
      category:
        type: string
      notes:
        type: string
  UpdateTransaction:
    type: object
    properties:
      id:
        type: integer
      date:
        type: string
      description: 
        type: string
      amount:
        type: integer
      type:
        type: string
      category:
        type: string
      notes:
        type: string

